### ISSUE TITLE
Run plugin on Build

### ISSUE THREAD

**Issue by AlemTuzlak** [forge42dev/vite-plugin-icons-spritesheet#11]
The plugin currently only runs in development, it should be possible to output build artifacts with it

**Comment by wKovacs64** [comment]
I assume this is more involved than simply removing the `mode` check?

**Comment by AlemTuzlak** [comment]
@wKovacs64 Added, please try with v2!

**Comment by wKovacs64** [comment]
> @wKovacs64 Added, please try with v2!

Works like a champ. 🎉 Thanks, Alem!
