### ISSUE TITLE
Doesn't do anything? (reproduction included)

### ISSUE THREAD

**Issue by wKovacs64** [forge42dev/vite-plugin-icons-spritesheet#2]
Hey Alem!👋 This looks cool, so I wanted to try it out but I can't seem to make it actually do anything (in dev nor when building for prod). It looks very simple, but I watched [the YT video](https://youtu.be/1yaMkLEY6LU?si=HPFTJp-hHQkgF0z1) just to make sure I wasn't doing something wrong. 😅 I must be having one of those days. What am I missing?!

Reproduction:

https://github.com/wKovacs64/remix-292-vite-spritesheet

(Note: I also cloned your repo and tried your example in `test-apps/remix-vite` but it doesn't work either.)

**Comment by AlemTuzlak** [comment]
@wKovacs64 Thank you so much for this repro, fixed it with v1.1.1 which is released, the issue was that it was trying to check if the file has the same content as before but if the file didn't exist it would not work

**Comment by AlemTuzlak** [comment]
Really?? 😮 Okay I'll investigate tomorrow again on the same repo, sorry about that 😕

**Comment by wKovacs64** [comment]
#4 only fixed dev, it still doesn't do anything when running `npm run build`. Updated the reproduction with v1.2.0.

**Comment by AlemTuzlak** [comment]
@wKovacs64 ahh, the reason behind that is because I disabled it in bundling so it doesn't pull any deps in

**Comment by wKovacs64** [comment]
@AlemTuzlak I don't know anything about authoring Vite plugins so I can't speak intelligently on the topic, but are you suggesting all Vite plugins include their own dependencies in the app bundle(s)? 🤯 

Some additional context: we consider all generated code to be build artifacts and therefore don't track it in source control. As such, we expect both `npm run dev` and `npm run build` to output the generated code. It doesn't sound like that's possible with this plugin, currently?

**Comment by AlemTuzlak** [comment]
@wKovacs64 It really depends on the Vite plugin, but now that I've thought about it this one probably wouldn't, It would probably be safe to just run it on build, let me look into this, I'll create a new issue instead.

It should be doable
