### ISSUE TITLE
Prevent inlining the SVG sprite

### ISSUE THREAD

**Issue by silvenon** [forge42dev/vite-plugin-icons-spritesheet#20]
My recommendation is, since the plugin knows the exact name of the SVG sprite, that it modifies the configuration to prevent asset inlining for it. The option to edit is [`build.assetsInlineLimit`](https://vitejs.dev/config/build-options.html#build-assetsinlinelimit), and the goal is to ignore inlining only for the SVG sprite, because inlining breaks the icons.

```js
{
  build: {
    assetsInlineLimit(filePath) {
      if (filePath.endsWith(fileName)) {
        return false
      }
    },
  },
}
```

If you agree, I think I can help here. I'm not sure whether plugins can compound this option, that would be great, it would be a shame if that option only gets overridden by whichever plugin "wins".

**Comment by AlemTuzlak** [comment]
Added it to the plugin, great idea!
