### ISSUE TITLE
Should this plugin auto-disable assetsInlineLimit?

### ISSUE THREAD

**Issue by bravo-kernel** [forge42dev/vite-plugin-icons-spritesheet#24]
Awesome plugin ❤️ 

Sanity check after reading the tickets and code: should this plugin automatically disable inlining the asset?

If so, it does not work for me on Windows + Vite. I still need to add this to `vite.config.ts`:

```ts
  build: {
    assetsInlineLimit: 0, // or SVG sprites will not show
  },
```

**Comment by AlemTuzlak** [comment]
Thank you! It should, but only the spritesheet you specify, nothing else. Could you create a repro? I actually developed this on windows + vite so I'm really surprised to hear it doesn't do it properly, did you specify the svg path?

**Comment by bravo-kernel** [comment]
Thank you for confirming (so quickly), just wanted to make sure.

I am running Gitbash so it might not be Windows 1-on-1. 

Do you mean specifying the svg path as done inside my vite config?

```ts
      withTypes: true, // True to generate TS types
      inputDir: "other/svg-icons", // Path to folder with svg icons
      outputDir: "app/components/ui/icons", // Path to folder with generated spritesheet and types
      typesOutputFile: "app/components/ui/icons/name.d.ts", // Path to generated type file (defaults to types.ts in outputDir)
      fileName: "sprite.svg", // Name of generated spritesheet (defaults to sprite.svg)
      cwd: process.cwd(), // The cwd, defaults to process.cwd()
      // formatter: "biome", // Formatter to use
      // pathToFormatterConfig: "./biome.json", // Path to formatter config file
      // Callback function that is called when the script is generating the icon name
      // This is useful if you want to modify the icon name before it is written to the file
      iconNameTransformer: (iconName) => iconName,
```

**Comment by AlemTuzlak** [comment]
@bravo-kernel yeah, it listens to that path, and then if it's matched it skips the inlining, I'm surprised that it doesn't work for you as I tested it out extensively to make sure I didn't miss anything for all possible scenarios

**Comment by bravo-kernel** [comment]
Forgot but... everything else works fantastic, watcher and all.

**Comment by bravo-kernel** [comment]
Yes, this is probably something silly on my end. 

I migrated from the "npm build"  method described at https://www.mattstobbs.com/optimal-icons-remix/ so I might have messed something up. Let me double check.

**Comment by bravo-kernel** [comment]
Code looks fine, still need the `vite.config.ts` setting or the SVG will not show.

Do you know of any existing vite repos using your plugin? Creating a repo will may become a bit difficult.

**Comment by AlemTuzlak** [comment]
We use it here https://discord.com/channels/770287896669978684/1309600313082384475

**Comment by bravo-kernel** [comment]
Looking at the ShoppingCart item from the RR7 Stack so closing (as this must be a me-issue).

![image](https://github.com/user-attachments/assets/1d9c948e-e368-4d3e-98ef-b0f595476623)

Thanks for confirming. Nice stack too 💯
